title:            The Margaret Sanger Papers Project
url:              ''
baseurl:          '/sanger-repotted'
logo:             'images/logo.png'

# permalink:        pretty
incremental:      true
encoding:         utf-8
exclude:          [Rakefile, README.md]

collections_dir: sections
collections:
  project:
    output: true
    permalink: '/project/:title:output_ext'
  aboutms:
    output: true
    permalink: '/aboutms/:title:output_ext'
  publications:
    output: true
    permalink: '/publications/:title:output_ext'
  newsletter:
    output: true
    permalink: '/newsletter/:title:output_ext'
  articles:
    output: true
    permalink: '/articles/:title:output_ext'
  documents:
    output: true
    permalink: '/documents/:title:output_ext'
  research:
    output: true
    permalink: '/research/:title:output_ext'

menu:
  - label: About Sanger
    sub:
      - label: Biographical Sketch
        link: aboutms/msbio.html
      - label: Birth Control Organizations
        link: aboutms/bc_organizations.html
      - label: The Sanger Archive
        link: aboutms/sanger_archive.html
      - label: "Sanger's Writings"
        link: aboutms/ms_writings.html
  - label: The Project
    sub:
      - label: About
        link: project/index.html
      - label: Staff
        link: project/staff.html
      - label: Interns
        link: project/internships.html
      - label: Funders
        link: project/funders.html
      - label: Reviews
        link: project/reviews.html
      - label: Editing at the MSPP
        link: project/editing.html
      - label: Support
        link: project/support.html
  - label: Publications
    sub:
      - label: About
        link: publications/index.html
      - label: Selected Papers of MS
        link: publications/book.html
      - label: Microfilm Edition
        link: publications/microfilm.html
      - label: Online Microfilm Edition
        link: publications/microfilm-online.html
      - label: Speeches and Articles
        link: 'https://estherkatz.org/sangerpapers/documents/'
      - label: Editorial Methods
        link: publications/editorial_methods.html
  - label: Newsletter
    sub:
      - label: About
        link: newsletter/index.html
      - label: Articles
        link: newsletter/articlelist.html
  - label: Documents Online
    sub:
      - label: About
        link: documents/index.html
      - label: Selected Writings
        link: documents/selected.html
      - label: Digital Edition
        link: 'https://estherkatz.org/sangerpapers/documents/'
      - label: MS and the Woman Rebel
        link: documents/mswomanrebel.html
      - label: Docs on Other Sites
        link: documents/othersites.html
  - label: Resources
    sub:
      - label: About
        link: research/index.html
      - label: "Editors' Notes"
        link: research/editorsnotes.html
      - label: National History Day
        link: research/nhday.html
      - label: Sanger Bibliography
        link: research/bibliography.html
      - label: Sanger Images
        link: research/images.html
      - label: Links
        link: research/links.html
  - label: Contact Us
    link: contactus.html
